<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scientific Calculator</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 20px;
        }
        .calculator {
            display: inline-block;
            text-align: left;
            border: 1px solid #ccc;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
        }
        .display {
            width: 100%;
            height: 50px;
            font-size: 18px;
            margin-bottom: 10px;
            text-align: right;
            padding: 5px;
        }
        .buttons {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 5px;
        }
        .button {
            padding: 15px;
            font-size: 18px;
            text-align: center;
            cursor: pointer;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        .button:hover {
            background-color: #e0e0e0;
        }
    </style>
</head>
<body>
    <div class="calculator">
        <input type="text" class="display" id="display" disabled>
        <div class="buttons">
            <button class="button" onclick="appendValue('7')">7</button>
            <button class="button" onclick="appendValue('8')">8</button>
            <button class="button" onclick="appendValue('9')">9</button>
            <button class="button" onclick="clearDisplay()">C</button>
            <button class="button" onclick="appendValue('4')">4</button>
            <button class="button" onclick="appendValue('5')">5</button>
            <button class="button" onclick="appendValue('6')">6</button>
            <button class="button" onclick="appendValue('/')">/</button>
            <button class="button" onclick="appendValue('1')">1</button>
            <button class="button" onclick="appendValue('2')">2</button>
            <button class="button" onclick="appendValue('3')">3</button>
            <button class="button" onclick="appendValue('*')">*</button>
            <button class="button" onclick="appendValue('0')">0</button>
            <button class="button" onclick="appendValue('.')">.</button>
            <button class="button" onclick="calculate()">=</button>
            <button class="button" onclick="appendValue('-')">-</button>
            <button class="button" onclick="appendValue('(')">(</button>
            <button class="button" onclick="appendValue(')')">)</button>
            <button class="button" onclick="appendValue('+')">+</button>
            <button class="button" onclick="calculateFunction('sin')">sin</button>
            <button class="button" onclick="calculateFunction('cos')">cos</button>
            <button class="button" onclick="calculateFunction('tan')">tan</button>
            <button class="button" onclick="calculateFunction('log')">log</button>
        </div>
    </div>

    <script>
        function appendValue(value) {
            document.getElementById('display').value += value;
        }

        function clearDisplay() {
            document.getElementById('display').value = '';
        }

        function calculate() {
            try {
                let result = eval(document.getElementById('display').value);
                document.getElementById('display').value = result;
            } catch {
                document.getElementById('display').value = 'Error';
            }
        }

        function calculateFunction(func) {
            try {
                let display = document.getElementById('display');
                let value = parseFloat(display.value);
                if (func === 'sin') {
                    display.value = Math.sin(value);
                } else if (func === 'cos') {
                    display.value = Math.cos(value);
                } else if (func === 'tan') {
                    display.value = Math.tan(value);
                } else if (func === 'log') {
                    display.value = Math.log10(value);
                }
            } catch {
                document.getElementById('display').value = 'Error';
            }
        }
    </script>
</body>
</html>
